language: python
cache: pip
python:
- '3.5'
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_2e3704f31d08_key -iv $encrypted_2e3704f31d08_iv
  -in swarm-master.tar.gz.enc -out swarm-master.tar.gz -d
- tar zxvf swarm-master.tar.gz && rm swarm-master.tar.gz
- echo "make deploy" > deploy.sh && chmod +x deploy.sh
- pip install -U pip
- pip install wheel
install:
- pip wheel -r requirements.txt
- pip install -r requirements.txt
script:
- cd ./src
- py.test --cov=./
- flake8 ./
- cd $TRAVIS_BUILD_DIR
deploy:
  skip_cleanup: true
  provider: script
  script: "$TRAVIS_BUILD_DIR/deploy.sh"
  on:
    branch: master
notifications:
  slack:
    rooms:
      secure: jiOEjw3NgzmO79r/QpKAL/I1iKheYQAkJgXwshdyPDAoWdnvmWHOrX28pkh+ADv0KQU1QDoGtrUihb6EfC4cB0VP9DDGLLXprR7lu25LphMDJG5v/r8Sua4p+woiHZhypaZizd1dOIwmydxdqlf0YCAM8efAzGJ6PbRF1RPeZ0+bo4AUAJhbQb1VpQ7PzZZ05BseN4dDQOb0WxDKK6clryEKS6drbiDHjx04UWfWWwl0KG9H5hNkwhcLuBZL1AVOfv6X7K3GxkhoZDy1STuTMSi2CnVhHcuUQMrgrmi4/tB+jo2ao+RfSJDEp7ukC7Rij72BBBoEMbUDWs2QW/hk1R3f7yo8BE5+RgwBHUK63Rx8TJgdHpsLk8N28MrtsV+49UM5+yBk+jmPn8e65i75Wz/1Q4exXktk0+LqQpZ7uSCuC5Cf+i55I33G+kMrZHLgrfORlHt97FJGHvsu1MPFqiABUYgw79bc56tUqD3oCWLHTJiduPs7Z1Gn9gGEXu1BL2L9xALGwlYEZgUPlf6/rOrm3yFGpDwH9ugNY06VRyiqtPtkhnp7qPTV/7mvgCzU5KOHwFKKTl4R2TxCRvksuQ56sofmBg4ohoIquSJWXfSKPenzEJvqzwM+OuXFxPZx0YAhNxX2CnWtjNHNwNWROZn7HIlbhht0p4WfPRgdejY=
