apiVersion: v1
kind: ReplicationController
metadata:
  name: porkguy-server-rc
spec:
  replicas: 1
  selector:
    app: porkguy-server
  template:
    metadata:
      labels:
        app: porkguy-server
    spec:
      imagePullSecrets:
      - name: myregistrykey
      containers:
      - name: porkguy-server
        image: lucemia/porkguy:latest
        command: ["python", "manage.py", "runserver", "0.0.0.0:8080"]
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"

